ge15 = read.csv("~/ge2017/ge_2015_results.csv")
ge10 = read.csv("~/ge2017/ge_2010_results.csv")
head(ge10)
data = cbind(ge10[,c("Constituency.Name","Electorate","Votes","Lab","Con","LD","Grn","UKIP","SNP")], data.frame(year=2010))
data = rbind(data, cbind(ge15[,c("Constituency.Name","Electorate","Lab","LD","UKIP","SNP")], data.frame(Con=ge15$C, Grn=ge15$Green,Votes=ge15$Valid.Votes, year=2015)))
View(data[order(data$Constituency.Name),])
euref = read.csv("~/ge2017/Revised estimates of leave vote in Westminster constituencies - demog_based_estimates.csv")
euref=data.frame(Constituency.Name=euref$Constituency, leave=euref$Figure.to.use, year=2016)
m = merge(data, euref[,c("Constituency.Name","leave")],by="Constituency.Name",all=T)
write.csv(x = m, file = "combined.csv")